config/routes.rb
CrossfitTracker::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :workout_fundamentals

  resources :fundamentals

  resources :authentications

  resources :workout_records

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "welcome/index"

  resources :workouts
  resources :users

  resources :boxes

  match 'sign_in' => 'welcome#new'
  match 'sign_up' => 'welcome#sign_up'
  match 'retrieve' => 'welcome#retrieve'

  root :to => 'workout_records#index'

end

app/models/workout.rb
class Workout < ActiveRecord::Base
  # constants
  TIME = "time".freeze
  AMRAP = "AMRAP".freeze
  WORKOUT_TYPES = [TIME, AMRAP]

  # associations
  has_many :workout_records, :dependent => :destroy
  has_many :workout_fundamentals, :dependent => :destroy
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  # GET /workouts
  # GET /workouts.json
  before_filter :authenticate_user!

  def index
    @workouts = Workout.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @workouts }
    end
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
    @workout = Workout.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @workout }
    end
  end

  # GET /workouts/new
  # GET /workouts/new.json
  def new
    @workout = Workout.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @workout }
    end
  end

  # GET /workouts/1/edit
  def edit
    @workout = Workout.find(params[:id])
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.new(params[:workout])

    respond_to do |format|
      if @workout.save
        format.html { redirect_to @workout, notice: 'Workout was successfully created.' }
        format.json { render json: @workout, status: :created, location: @workout }
      else
        format.html { render action: "new" }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /workouts/1
  # PUT /workouts/1.json
  def update
    @workout = Workout.find(params[:id])

    respond_to do |format|
      if @workout.update_attributes(params[:workout])
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout = Workout.find(params[:id])
    @workout.destroy

    respond_to do |format|
      format.html { redirect_to workouts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
  def workout_string(w)
    
    s="#{w.rounds} rounds: "
    w.workout_fundamentals.each do |wf|
      name=Fundamental.find(wf.fundamental_id).try(:name)
      
      count=wf.count.to_s
      distance=wf.distance.to_s
      weight=wf.weight==nil ? " " : " #{wf.weight.to_s}# "
      mod=count+distance+weight

      
      s=s+"#{mod} #{name}, "
    end
    s.chomp(", ")
  end
end

app/views/workouts/_form.html.erb
<%= simple_form_for @workout do |f| %>
  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% @workout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name, :placeholder => 'Name', :input_html => { :class => "input_text" } %>
 <%= f.input :rounds, :placeholder => 'Rounds', :input_html => { :class => "input_text" } %>
  <%= f.input :content,  :placeholder => 'Details of Workout', :input_html => { :class => "input_text_area input_text" } %>
  <%= f.input :workout_type, :collection => Workout::WORKOUT_TYPES, :input_html => { :class => "input_select" } %>
  <br />
  <%= f.button :submit, :class => "submit_button"%>
  <%= link_to 'Cancel', workouts_path, :class => "cancel_button" %>
<% end %>

app/views/workouts/edit.html.erb
<h1>Editing Workout</h1>

<%= render 'form' %>

app/views/workouts/index.html.erb
<h1>Listing workouts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @workouts.each do |workout| %>
  <tr>
    <td><%= workout.name %></td>
    <td><%= workout_string  workout %></td>
    <td><%= workout.date %></td>
    <td><%= link_to 'Show', workout %></td>
    <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
    <td><%= link_to 'Destroy', workout, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wod', new_workout_path %>

app/views/workouts/new.html.erb
<h1>New workout</h1>

<%= render 'form' %>

app/views/workouts/show.html.erb
<% fb_timeline_meta current_url, @workout.name, @workout.content %>

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @workout.name %>
</p>

<p>
  <b>Rounds:</b>
  <%= @workout.rounds %>
</p>

<p>
  <b>Workout String:</b>
  <%= workout_string(@workout) %>
</p>



<p>
  <b>Content:</b>
  <%= @workout.content %>
</p>

<p>
  <b>Date:</b>
  <%= @workout.date %>
</p>



<p>
<table>
  <tr>
    <th>Workout</th>
    <th>Fundamental</th>
    <th>Count</th>
    <th>Weight</th>
    <th>Distance</th>

    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @workout.workout_fundamentals.each do |workout_fundamental| %>
  <tr>
    <td><%= workout_fundamental.workout.try(:name) %></td>
    <td><%= Fundamental.find(workout_fundamental.fundamental_id).try(:name) %></td>
    <td><%= workout_fundamental.count %></td>
    <td><%= workout_fundamental.weight %></td>
    <td><%= workout_fundamental.distance %></td>

    <td><%= link_to 'Show', workout_fundamental %></td>
    <td><%= link_to 'Edit', edit_workout_fundamental_path(workout_fundamental) %></td>
    <td><%= link_to 'Destroy', workout_fundamental, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Workout fundamental', new_workout_fundamental_path %>

</p>

<p>
 <div id="fb-root"></div>
 <script src="http://connect.facebook.net/en_US/all.js"></script>
 <script>
      FB.init({ 
          appId:'150346335059375', cookie:true, 
          status:true, xfbml:true, oauth:true
      });
      </script>
 <script type="text/javascript">
 function postCook()
 {
     FB.api('/me/mproll-crossfit:log' + 
                 '&workout=<%=current_url%>','post',
                 function(response) {
	console.log(response)
         if (!response || response.error) {
                 alert('Error occured');
         } else {
             alert('Post was successful! Action ID: ' + response.id);
             }
     });
 }
 </script>
	<form>
     <input type="button" value="Log this Exercise on FB" onclick="postCook()" />
 </form>	
</p>


<%= link_to 'Edit', edit_workout_path(@workout) %> |
<%= link_to 'Back', workouts_path %>