config/routes.rb
CrossfitTracker::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :workout_fundamentals

  resources :fundamentals

  resources :authentications

  resources :workout_records

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "welcome/index"

  resources :workouts
  resources :users

  resources :boxes

  match 'sign_in' => 'welcome#new'
  match 'sign_up' => 'welcome#sign_up'
  match 'retrieve' => 'welcome#retrieve'

  root :to => 'workout_records#index'

end

app/models/fundamental.rb
class Fundamental < ActiveRecord::Base

end

app/controllers/fundamentals_controller.rb
class FundamentalsController < ApplicationController
  # GET /fundamentals
  # GET /fundamentals.json
  def index
    @fundamentals = Fundamental.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fundamentals }
    end
  end

  # GET /fundamentals/1
  # GET /fundamentals/1.json
  def show
    @fundamental = Fundamental.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fundamental }
    end
  end

  # GET /fundamentals/new
  # GET /fundamentals/new.json
  def new
    @fundamental = Fundamental.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fundamental }
    end
  end

  # GET /fundamentals/1/edit
  def edit
    @fundamental = Fundamental.find(params[:id])
  end

  # POST /fundamentals
  # POST /fundamentals.json
  def create
    @fundamental = Fundamental.new(params[:fundamental])

    respond_to do |format|
      if @fundamental.save
        format.html { redirect_to @fundamental, notice: 'Fundamental was successfully created.' }
        format.json { render json: @fundamental, status: :created, location: @fundamental }
      else
        format.html { render action: "new" }
        format.json { render json: @fundamental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fundamentals/1
  # PUT /fundamentals/1.json
  def update
    @fundamental = Fundamental.find(params[:id])

    respond_to do |format|
      if @fundamental.update_attributes(params[:fundamental])
        format.html { redirect_to @fundamental, notice: 'Fundamental was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @fundamental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fundamentals/1
  # DELETE /fundamentals/1.json
  def destroy
    @fundamental = Fundamental.find(params[:id])
    @fundamental.destroy

    respond_to do |format|
      format.html { redirect_to fundamentals_url }
      format.json { head :ok }
    end
  end
end

app/helpers/fundamentals_helper.rb
module FundamentalsHelper
end

app/views/fundamentals/_form.html.erb
<%= form_for(@fundamental) do |f| %>
  <% if @fundamental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fundamental.errors.count, "error") %> prohibited this fundamental from being saved:</h2>

      <ul>
      <% @fundamental.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fundamentals/edit.html.erb
<h1>Editing fundamental</h1>

<%= render 'form' %>

<%= link_to 'Show', @fundamental %> |
<%= link_to 'Back', fundamentals_path %>

app/views/fundamentals/index.html.erb
<h1>Listing fundamentals</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fundamentals.each do |fundamental| %>
  <tr>
    <td><%= fundamental.name %></td>
    <td><%= link_to 'Show', fundamental %></td>
    <td><%= link_to 'Edit', edit_fundamental_path(fundamental) %></td>
    <td><%= link_to 'Destroy', fundamental, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fundamental', new_fundamental_path %>

app/views/fundamentals/new.html.erb
<h1>New fundamental</h1>

<%= render 'form' %>

<%= link_to 'Back', fundamentals_path %>

app/views/fundamentals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @fundamental.name %>
</p>


<%= link_to 'Edit', edit_fundamental_path(@fundamental) %> |
<%= link_to 'Back', fundamentals_path %>