config/routes.rb
CrossfitTracker::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :workout_fundamentals

  resources :fundamentals

  resources :authentications

  resources :workout_records

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "welcome/index"

  resources :workouts
  resources :users

  resources :boxes

  match 'sign_in' => 'welcome#new'
  match 'sign_up' => 'welcome#sign_up'
  match 'retrieve' => 'welcome#retrieve'

  root :to => 'workout_records#index'

end

app/views/shared/_links.erb
<%- if action != 'sign_in' %>
  <%= link_to "Sign in", sign_in_path(@resource_name) %>
<% end -%>

<%- if action != 'sign_in' -%>
|
<%- end -%>

<%- if @devise_mapping.registerable? && action != 'sign_up' %>
  <%= link_to "Sign up", sign_up_path(@resource_name) %>
<% end -%>

<%- if action != 'retrieve' && action != 'sign_up' -%>
|
<%- end -%>

<%- if @devise_mapping.recoverable? && action != 'retrieve' %>
  <%= link_to "Forgot password?", retrieve_path(@resource_name) %><br />
<% end -%>

<%- if @devise_mapping.confirmable? && action != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(@resource_name) %><br />
<% end -%>

<%- if @devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && action != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(@resource_name) %><br />
<% end -%>